# This Dockerfile is copy-pasted into our main docs at /docs/handbook/deploying-with-docker.
# Make sure you update both files!
FROM onboardingdesignsystem:local as installer

# production stage
FROM nginx:stable as production-stage
COPY --from=installer /home/app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY ./apps/docs/docker/nginx.conf /etc/nginx/
EXPOSE 6006

CMD ["nginx", "-g", "daemon off;"]
